# This file describes a Fastly Compute package. To learn more visit:
# https://www.fastly.com/documentation/reference/compute/fastly-toml

authors = ["nisse@tnfgruppen.com"]
cloned_from = "https://github.com/fastly/compute-starter-kit-javascript-default"
description = "Object Storage demo for 2025 SKO by Nils Boman and Antoine Brossault"
language = "javascript"
manifest_version = 3
name = "OSDemo"
service_id = ""

[local_server]

[scripts]
  build = "npm run build"
  post_init = "npm install"
